### ISSUE TITLE
Use JSX

### ISSUE THREAD

**Issue by nwinch** [Prismatik/redbeard-admin#4]
I suggest we should stick to using JSX instead of React API for any redbeard react work.  Most of our react projects use JSX, is there any reason we shouldn't use it for this?

**Comment by davidbanham** [comment]
So, we should still move to JSX. However, the new strategy is to build out the UI library, then use it to build the next iteration of the admin UI.

In that world, it probably doesn't make sense to invest time in porting the existing components from API to JSX where they sit. If we decide to take any of these components across to the UI lib (which I hope we do!) we can do the conversion work at that point, once it's certain they're being taken forward.

On that note, I propose closing this issue. We've still got the project/company-wide directive of "use JSX" in place, but we're removing the "Port this code to JSX right now" directive.

Sane?

**Comment by nwinch** [comment]
I reckon it'll be easier going for me just to change API -> JSX when I come across it.  I think at this point it'd slow me down a bit having to continue with API.  So I could just convert the stuff I'm dealing with for whatever the upcoming tasks are, that would make me happy :)

So yeah as you say, eventually the admin will be made up of our UI lib components - which will be in JSX - but I think for my sanity in the interim, I just change stuff where it makes sense, but if it's like a huge component or something and it's gonna take a while, I won't bother and we can just keep rolling.  Given the modularity of things, it won't be a deal breaker to have some components API, and some JSX I reckon, as we know the eventual outcome is JSX.

Overall I'll use common sense - if it's gonna take time I don't have, I won't worry about it :)

For sure, it can be closed.

**Comment by davidbanham** [comment]
Cool, I'm happy with that. Leave it up to the implementer whether to quickly refactor or press on.
